# Generated by Django 5.2.8 on 2025-11-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dependencies',
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to='tasks.task'),
        ),
    ]
